import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// Components
import SideNavigation from "@/components/common/navigation/SideNavigation";
// Shadcn UI
import { Toaster } from "@/components/ui/toaster"
// 전역 CSS
import "@/styles/globals.css";

const inter = Roboto({ subsets: ["latin"], weight:["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Shadcn UI -Todoboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideNavigation />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
